### ISSUE TITLE
`No TestSuite is selected` in Git mode after deleting the project and creating the same one

### ISSUE THREAD

**Issue by kgevorkyan** [saveourtool/save-cloud#1002]
If we will create some new project and run execution in Git mode, then `save` will detect testSuites, create corresponding data in our storage and so on.

However, if we will delete this project from DB and then create the same one and create the same execution, then we will get
```bash
[reactor-http-epoll-6] ERROR reactor.core.publisher.Operators - Operator called default onErrorDropped
reactor.core.Exceptions$ErrorCallbackNotImplemented: java.lang.IllegalArgumentException: No TestSuite is selected
Caused by: java.lang.IllegalArgumentException: No TestSuite is selected
        at com.saveourtool.save.preprocessor.controllers.DownloadProjectController.getSingleVersion(DownloadProjectController.kt:190)
```

Probably there are appear some conflicts with paths in our storage, after removing project from DB and creating the same one, therefore we can't find any `testSuites`

For now this problem disappear after cleaning the storage too

**Comment by nulls** [comment]
need to review cleanup policy for `test suites source` -> `test suites` -> `project`
