### ISSUE TITLE
Check the branch name on the frontend

### ISSUE THREAD

**Issue by akuleshov7** [saveourtool/save-cloud#1011]
When we pass the value to the test source and select branch - it should start with origin/

We should validate it in the frontend.

Also we need to propagate GIT errors to the frontend properly.

**Comment by petertrr** [comment]
> Also we need to propagate GIT errors to the frontend properly.

#331

**Comment by nulls** [comment]
it can be done on validation on creating TestSuitesSource (as we made validation for Git Credentials)

**Comment by nulls** [comment]
Implemented in #1210
