### ISSUE TITLE
After the creation of new test sources we rework logic of standard tests

### ISSUE THREAD

**Issue by akuleshov7** [saveourtool/save-cloud#1019]
We need to enhance the UI for standard tests also for it. 

<img width="1007" alt="image" src="https://user-images.githubusercontent.com/58667063/183857911-50d4776f-87ca-4d7f-b684-0072b590527a.png">

@sanyavertolet you made great improvements for contests, may be you can help here also

**Comment by akuleshov7** [comment]
@nulls please give suggestions

**Comment by nulls** [comment]
@akuleshov7 we can re-use `TestSuiteSelector` added by @sanyavertolet

**Comment by akuleshov7** [comment]
@sanyavertolet can we rework test suite selector, so It will have the following:
1) grouping by some feature (for example tags)
2) button select/unselect ALL
3) may be search by name (as we have when we add user in organization)

**Comment by nulls** [comment]
Need to add this logic for regular execution run after #1028

**Comment by akuleshov7** [comment]
@sanyavertolet could you please move selector to standard tests
