### ISSUE TITLE
Properly support results of the contests

### ISSUE THREAD

**Issue by akuleshov7** [saveourtool/save-cloud#1035]
1. All contest run results should be properly stored in a database and linked to the project. This should be elegantly be done in the same manner as execution history is done - the best scenario is when we reuse all the related logic to existing run:
- You can have a normal execution run;
- Have a table for contest results with links to these execution - something like this: **Score, ExecutionId, Contest** ;
- As executions are linked to the project already - there will not be any problems to show/calculate total score for the project on the frontend. Also it will be easy to find the champion in contests and show results dashboard on the contests page.

3. We need to fill in two tabs on contests View: 
- Participants (a good example is [here](https://www.hackerrank.com/leaderboard));
- Results only for **your** projects. That is a tough task, because you we need to show results for **all projects** where user is added. For example - if user added to both diktat and ktlint and both of them were participating in contests - we should show them.

**Comment by sanyavertolet** [comment]
The frontend part is done with #1081 and #1108. Backend part will be done as #1115
