### ISSUE TITLE
Debug info is not found regression

### ISSUE THREAD

**Issue by akuleshov7** [saveourtool/save-cloud#1038]
<img width="1670" alt="image" src="https://user-images.githubusercontent.com/58667063/184554052-b19961d4-78d0-4ada-aac8-524ef0f444df.png">

https://saveourtool.com/#/CQFN.org/Diktat/history/execution/188

**Comment by akuleshov7** [comment]
Linked with #1037. But in this issue you should also **PROPERLY** cover 404 case.

**Comment by petertrr** [comment]
rn saveourtool.com has a version without #1024 (deployed version is `147+0cd164a`, the fix appeared in `152+345e9c4`). The issue you have described should be fixed by #1024

**Comment by petertrr** [comment]
With the new version the row is expanded and debug info is displayed. Closing this.
