### ISSUE TITLE
Incorrect missing/matched calculation

### ISSUE THREAD

**Issue by akuleshov7** [saveourtool/save-cloud#1039]
<img width="1709" alt="image" src="https://user-images.githubusercontent.com/58667063/184554204-6a2b5653-3b21-4d09-a343-95da32a13064.png">

Please after fixing - also add diktat smoke tests and test examples from master/main of SAVE-cli.

This significantly affects precision and recall.

**Comment by nulls** [comment]
Valid cases. `0` is for fix plugin.
Agreed to change it to `N/A` for them. Need to investigate where it should be done (save-cli vs save-cloud)

**Comment by nulls** [comment]
Need to support changes from https://github.com/saveourtool/save-cli/pull/437
