### ISSUE TITLE
Change/generate URL for these tabs

### ISSUE THREAD

**Issue by Arrgentum** [saveourtool/save-cloud#1044]
Is it possible to change/generate URL for these tabs that can be shared (may be using state):

<img width="480" alt="image" src="https://user-images.githubusercontent.com/58667063/184435413-9c736b58-e313-4072-a201-4619e6063f71.png">

If you open this URL - you have direct link to the view with this tab open. It can be a huge task to do it in common for views - if yes - please do it in a separate task. 

_Originally posted by @akuleshov7 in https://github.com/saveourtool/save-cloud/issues/998#issuecomment-1213388911_

**Comment by Arrgentum** [comment]
There is a problem with navigating to the tab addresses in the OrganizationView.kt @akuleshov7

In the App.kt address of the tab in OrganizationView.kt has the form:
path = "/:owner/:the tab"
Address of the project name in OgranizationView.kt has the form:
path = "/:owner/:name"

The React router cannot determine where to go.

In my opinion, the best solution is register these tab addresses (tools, tests, info, settings) separately and prohibit the creation of projects with such names

**Comment by petertrr** [comment]
I think we should just make those URLs less pretty and more easy to work with. Consider github: main page of organization is `https://github.com/saveourtool`, but if you navigate to the settings tab you get at `https://github.com/organizations/saveourtool/settings/profile`. With repos its different thoug: `https://github.com/saveourtool/save-cloud` and `https://github.com/saveourtool/save-cloud/settings`
