### ISSUE TITLE
If test suite source creation has failed, request can't be send without page reload

### ISSUE THREAD

**Issue by petertrr** [saveourtool/save-cloud#1062]
Suspicious code: 
https://github.com/saveourtool/save-cloud/blob/084d5bf305d7ce6a957223136c707f7caaa65729/save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/TestSuiteSourceCreationComponent.kt#L106-L119

For some reason `post` returns 404, but we still attempt to decode JSON and fail. Inside `useRequest` `setIsSending(false)` is never called and submit button doesn't work anymore.

Handling returned value should be performed outside of `useRequest`; callback returned by `useRequest` should be wrapped together with decoding logic in a separate lambda.

Version of save-frontend: 58cd0d5b8c8c0691737edcdff312fab9c001473a

**Comment by nulls** [comment]
@sanyavertolet I have added `resposnse.isConflict` as you asked

**Comment by sanyavertolet** [comment]
Fixed by @nulls in #1056
