### ISSUE TITLE
Response handler doesn't handle errors properly

### ISSUE THREAD

**Issue by sanyavertolet** [saveourtool/save-cloud#1067]
In some way frontend response handler doesn't handle `404` errors with default response handler. Probably other errors are also processed in a wrong way as well as changing handler does not fix an issue

**Comment by petertrr** [comment]
![image](https://user-images.githubusercontent.com/23018090/185640003-ca322544-db6a-4406-a036-7bcb29459921.png)
This behavior has been explicitly disabled by @Cheshiriks in #935, but it should also be set based on `redirectToFallbackView`
