### ISSUE TITLE
Orchestrator shouldn't stop agents if backend is unavailable

### ISSUE THREAD

**Issue by petertrr** [saveourtool/save-cloud#1075]
Now if agents keep heartbeating, but backend is unavailable and `agentService.updateAgentStatusesWithDto` fails with network error, orchestrator will treat agents as abnormal and terminate them after some time. This is incorrect; if agents keep heartbeating in `IDLE` state, execution can still be finished once backend is back online

**Comment by akuleshov7** [comment]
fail-safety can be very important
