### ISSUE TITLE
Test suite source validation

### ISSUE THREAD

**Issue by petertrr** [saveourtool/save-cloud#1096]
After test suite source is fetched, we should store and display validations, including among others:
* Whether source contains suites with plugins that have zero tests
* Whether source contains suites with wildcard mode (not handled well by save-cloud currently?)

This includes calculating these validations, storing them in the storage and support them on the frontend

---

Tasks, as discussed with @nulls:
 * Front-end
   * [X] #1810
   * [ ] Display the current fetch status ("Fetching...", "Completed", "Errors encountered", "Time-out", "Preprocessor unavailable") when (re-)fetching
   * [ ] Display the last fetch status ("Completed", "Errors encountered") when viewing tests (the _Tests_ tab within an organization), using data from the `tests_source_version` and `tests_source_snapshot` tables.
 * Back-end
   * TBD
 * Preprocessor
   * [X] #1778
   * [x] #1955 
   * [x] #1956 
   * [ ] Refactor `TestSuitesPreprocessorController#doFetchTests()` and the underlying calls
      * [ ] The snapshot should be always saved (`TestPreprocessorToBackendBridge#saveTestsSuiteSourceSnapshot()`), even in case of validation errors. This is necessary, so that a malformed snapshot is never re-fetched again.
      * [ ] The `tests_source_snapshot` table, along with the corresponding DTO, should be enriched with `isSuccessful` and `errorMessage` fields
      * [ ] `TestDiscoveringService#detectAndSaveAllTestSuitesAndTests()` should perform the following operations, in order:
         1. detect test suites and tests
         2. validate test suites and tests
         3. update the saved snapshot with status and error messages, if any
         4. save test suites and tests, if the validation succeeded

**Comment by akuleshov7** [comment]
Andrey did a lot of related things, probably we will open a new issue, when needed
