### ISSUE TITLE
Preprocessor: ISE with no explicit branch

### ISSUE THREAD

**Issue by petertrr** [saveourtool/save-cloud#1101]
To reproduce, create a new test suite source from URL https://github.com/saveourtool/save-cli/ and don't specify a branch. On fetching, the following error occurs:
```
java.lang.IllegalStateException: Couldn't detect hash of HEAD for https://github.com/saveourtool/save-cli/
	at com.saveourtool.save.preprocessor.utils.GitUtilKt.detectLatestSha1(GitUtil.kt:55)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
...
Original Stack Trace:
		at com.saveourtool.save.preprocessor.utils.GitUtilKt.detectLatestSha1(GitUtil.kt:55)
		at com.saveourtool.save.preprocessor.controllers.TestSuitesPreprocessorController.detectLatestVersion$lambda-6(TestSuitesPreprocessorController.kt:75)
...
```
Preprocessor at 974481597e027c85b4298fb0bad8f1c875c7efd9

**Comment by sanyavertolet** [comment]
@nulls suggested to detect main branch automatically using GitHub api

**Comment by nulls** [comment]
yes, I think we should make branch name is mandatory field. Will support it in scope of #1105

**Comment by petertrr** [comment]
> using GitHub api

This will require vendor-specific logic in our code. I think we can simply clone default branch already in preprocessor, without necessarily filling this field in the DB

**Comment by nulls** [comment]
Not relevant after https://github.com/saveourtool/save-cloud/pull/1210
