### ISSUE TITLE
Integration problems

### ISSUE THREAD

**Issue by akuleshov7** [saveourtool/save-cloud#1118]
1) save cli language limitations (remove python limitations)
2) Nariman’s idea: #1127
3) runConfigPattern in readme
4) setup.sh support #1120

**Comment by petertrr** [comment]
> 1. save cli language limitations (remove python limitations)
> 3. runConfigPattern in readme

https://github.com/saveourtool/save-cli/pull/444

**Comment by akuleshov7** [comment]
done
