### ISSUE TITLE
 Construct `execFlags` based on tags from `TestSuite`, mapping of `tag` to `execFlags` can be provided by consumers

### ISSUE THREAD

**Issue by nulls** [saveourtool/save-cloud#1127]

**Comment by petertrr** [comment]
Should this be done only in save-cloud or in save-cli too? We have suites and tags from `save.toml`s, so it seems doable in both.

**Comment by nulls** [comment]
I think it should be done in save-cli on `save.toml` level

**Comment by akuleshov7** [comment]
Let's even close this. I don't think we can do it
