### ISSUE TITLE
Add more targets for `save-agent`

### ISSUE THREAD

**Issue by nulls** [saveourtool/save-cloud#1128]
Currently, `save-agent` is built only for `linuxX64`.
We can add more targets like `jvm`. It should simplify debugging and local running

**Comment by petertrr** [comment]
Let's maybe narrow it down to only JVM, because previously we tried to build agent for mingX64 but with no real benefits. JVM can be good though.

**Comment by nulls** [comment]
> JVM can be good though.

Fully agree, Also we can add tests on JVM.

Currently we have a single test for linuxX64 which expects windows as launch system. Looks like it doesn't work
