### ISSUE TITLE
Synchronize `Agent ID` and `container name`

### ISSUE THREAD

**Issue by nulls** [saveourtool/save-cloud#1163]
Agents has `Agent ID` which displayed on `/history/execution/{executionId}` and `container name` which is used on grafana for example.

It will be useful to have an information about `container name` on execution history: there we know where execution are run

**Comment by petertrr** [comment]
`Agent ID` is actually a container ID in terms of Docker (it's just displayed weirdly on our frontend) and this information should be enough to identify the container. I don't think we need to store this information too.

**Comment by nulls** [comment]
> this information should be enough to identify the container

This information is enough, but it's easy to have `container name` information on execution history to search required logs on grafana for particular test
