### ISSUE TITLE
Bug on ContestView with invalid  URL

### ISSUE THREAD

**Issue by Cheshiriks** [saveourtool/save-cloud#1165]
When entering an invalid contest name in the url, we stay on the original page instead of going to 404
<img width="644" alt="Contest" src="https://user-images.githubusercontent.com/50615459/188468832-810ed916-04d9-423c-8f74-4f0b36ef8754.PNG">

**Comment by akuleshov7** [comment]
same with projects and organizations?

**Comment by Cheshiriks** [comment]
> same with projects and organizations?

No. Only contests
