### ISSUE TITLE
Sandbox support: we need to support easy-checks for users 

### ISSUE THREAD

**Issue by akuleshov7** [saveourtool/save-cloud#1167]
1. We need to create a new VIEW, where users will be able to check their configs
2. It should be like diktat demo 
3. Has 2 input windows (config, test) and 1 output window with debug info

![image](https://user-images.githubusercontent.com/58667063/190160382-a75cbd5c-f5c5-4983-a416-edc4815e8b1f.png)

**Comment by petertrr** [comment]
We also were talking about improved support in save-cli:
* Better (clear and readable) step-by-step logging: which test files have matched, why, which options have been used to extract warnings
* This information could be additionally written into a separate structured file (JSON?) that could be easily parsed for displaying in save-cloud-frontend

**Comment by petertrr** [comment]
Another idea - we can base the new view on the existing one with public tests under contests. Then before submitting execution for a contest the user will be able to test their tool on a public test.

**Comment by akuleshov7** [comment]
![image](https://user-images.githubusercontent.com/58667063/189941864-0dc17393-60af-4087-b49c-1a4466970159.png)

**Comment by akuleshov7** [comment]
The idea is changed a little bit:

![image](https://user-images.githubusercontent.com/58667063/190159928-0943716f-f8e5-495f-9226-5b9672ccd892.png)

**Comment by nulls** [comment]
- [ ] https://github.com/saveourtool/save-cloud/issues/1228
