### ISSUE TITLE
404 for latest execution info from `run` table

### ISSUE THREAD

**Issue by nulls** [saveourtool/save-cloud#1227]
From main page of project we get: https://saveourtool.com/#/CQFN.org/Diktat/history/execution/212 
But from `Run` tab we get: https://saveourtool.com/#/project/CQFN.org/Diktat/run/history/execution/212 which leads to 404

**Comment by petertrr** [comment]
@Arrgentum also please use `NavigateFunctionContext.navigate` instead of changing `window.location.href` like in #1216
