### ISSUE TITLE
Switch from `kotlin-react-table` to `kotlin-tanstack-react-table` (i.e. v7 -> v8)

### ISSUE THREAD

**Issue by petertrr** [saveourtool/save-cloud#1243]
As stated at https://github.com/JetBrains/kotlin-wrappers/tree/master/kotlin-react-table, this library is archived (i.e. fixed at react-table v7?) and should be replaced with `kotlin-tanstack-react-table`, which is a wrapper around react-table v8.
Migration guide for JS/TS: https://github.com/TanStack/table#migrating-from-react-table-v7

**Comment by nulls** [comment]
need to remove exclusion from renovate.json after migration
