### ISSUE TITLE
Redirect `/#/**` -> `/?#/**` on `ProjectView`

### ISSUE THREAD

**Issue by sanyavertolet** [saveourtool/save-cloud#1271]
After editing description of a project on `RUN` tab on `ProjectView` and attempting to save changes (or cancel them), we are being redirected to `/?#/project/{organizationName}/{projectName}/run`, which breaks the tab logic implemented by @Arrgentum.

### Steps to reproduce:
https://user-images.githubusercontent.com/35039155/193014212-75dcb174-f4f3-4882-b283-41137dc40944.mov

**Comment by Arrgentum** [comment]
As it turned out, this is a common mistake when clicking on most of the buttons on saveoutrools
