### ISSUE TITLE
Creating a user via external OAuth provider will fail if there's a name conflict

### ISSUE THREAD

**Issue by 0x6675636b796f75676974687562** [saveourtool/save-cloud#1291]
Consider a user wants to authenticate in a _save-cloud_ instance using a GitHub or any other OAuth provider.

If a user with the same name already exists (e. g.: with a different _source_, like `basic`, `dex`, etc.), the login process will **fail**, and the front-end will prompt for _HTTP Basic_ auth credentials.

The new user will get created in the inactive state.

```sql
select id, name, source, is_active from user where name like '0x%';
```

| id | name | source | is_active |
|--|--|--|--|
| 14 | 0x6675636b796f75676974687562 | basic | true |
| 18 | 0x6675636b796f75676974687562 | github | false |

```sql
select user_id, name, source from original_login where name like '0x%';
```
| user_id | name | source |
|--|--|--|
| 14 | 0x6675636b796f75676974687562 | basic |
| 18 | 0x6675636b796f75676974687562 | github |

Related: #1357

**Comment by petertrr** [comment]
> If a user with the same name already exists (e. g.: with a different source, like basic, dex, etc.), the login process will fail, and the front-end will prompt for HTTP Basic auth credentials.

I thought that one of the intended consequences of `original_login` table introduction was to solve this problem: if there is a name conflict, the user is redirected to registration page and is asked to choose a different login (this is what `isActive == false` is intended for). However, looks like we don't support merging different accounts in any way other than manually adding mappings `user -> original_logins`

**Comment by Cheshiriks** [comment]
Everything is so, we will not be able to understand for ourselves that this is the same person, and not a new one with the same name.
And we don’t have a process for combining different accounts yet. This, as everywhere else, should already be done when the user is logged in with some data and wants to add a new account to it.

**Comment by akuleshov7** [comment]
will be covered with #1357
