### ISSUE TITLE
[Sandbox] setup.sh can be uploaded by two ways

### ISSUE THREAD

**Issue by nulls** [saveourtool/save-cloud#1295]
`setup.sh` is a file. It can be uploaded by file uploader and as a text file.
Need to synchronize them:
* when it's uploaded by text file -- it should be selected
* when it's uploaded by file uploader -- code editor should be updated

Also, need to try make this file as optional

**Comment by sanyavertolet** [comment]
As discussed with @nulls, uploading `setup.sh` with file uploader should be forbidden.
