### ISSUE TITLE
[EPIC] Authorization service for SAVE cloud

### ISSUE THREAD

**Issue by akuleshov7** [saveourtool/save-cloud#1299]
Need to create a service that will unify all authorisation logic: for backend, sandbox and other future tools.

**Comment by akuleshov7** [comment]
@kgevorkyan as I can see - we already do it with api-gateway. Do you remember the problem?

**Comment by kgevorkyan** [comment]
The main logic was implemented long time ago, also we extract all our `auth` logic into the separate module `auth-service`,

However, now it's not really the service. Someday we planned to make the real `service`, to which all of our components will address to, when they need the `auth`.

It's kind of big task, and my investigations gave no valuable results, the are several approaches how we can do it, e.g. with help of `dex`, but there is too little amount of documentation, so it was postponed

Actually, I don't know, **will we do it at all one day or not**

It also could be connected with https://github.com/saveourtool/save-cloud/pull/1247 and https://github.com/saveourtool/save-cloud/pull/1238

**Comment by nulls** [comment]
Will be partially implemented by https://github.com/saveourtool/save-cloud/issues/2336
