### ISSUE TITLE
"Unexpected JSON token" when viewing execution history

### ISSUE THREAD

**Issue by 0x6675636b796f75676974687562** [saveourtool/save-cloud#1309]
The instance at [saveourtool.com](https://saveourtool.com), deployed from 5776e4a3105d6f7da2c75c34f4bae670d04fd1a0:

```
Error when fetching data: Unexpected JSON token at offset 319: Encountered an unknown key 'contestName' at path: $[0].score Use 'ignoreUnknownKeys = true' in 'Json {}' builder to ignore unknown keys. JSON input: ....."kotlin-diktat","score":null,"contestName":null}]
```

![image](https://user-images.githubusercontent.com/73111822/195147406-22b7b091-c2df-4cee-92c8-1fb7cbf8e842.png)

**Comment by nulls** [comment]
Need to clean site's cache -- old version of frontend tries to communicate with new version of backend

**Comment by akuleshov7** [comment]
Yes, this is the problem that your backend schema differs from frontend
