### ISSUE TITLE
A `FINISHED` execution where all tests have the `INTERNAL_ERROR` status is displayed in green in the front-end

### ISSUE THREAD

**Issue by 0x6675636b796f75676974687562** [saveourtool/save-cloud#1317]
![image](https://user-images.githubusercontent.com/73111822/195602779-e1aeb727-8419-424a-8a1f-907780954c6e.png)

Now, execution history:

![image](https://user-images.githubusercontent.com/73111822/195603026-5f02c09e-99ce-44c3-9d63-92b8de2e8f85.png)

**Comment by sanyavertolet** [comment]
Could not reproduce the bug on frontend, probably something is wrong (or used to be wrong) with backend.
