### ISSUE TITLE
Public tests and permissions sharing

### ISSUE THREAD

**Issue by akuleshov7** [saveourtool/save-cloud#1350]
We need to finalise permission management for test suites. We should be able to make:
- [x] public suites (https://github.com/saveourtool/save-cloud/pull/1337)
- [x] private suites (https://github.com/saveourtool/save-cloud/pull/1337)
- [x] shared with particular organisations (https://github.com/saveourtool/save-cloud/pull/1276)

This is a part of #1219

**Comment by sanyavertolet** [comment]
1. Remove logic for super admins from TestSuitePermissionEvaluator
2. Split different modes of permission management (PUBLISH and TRANSFER)
3. Fix minor bugs like 
4. Check debounce
5. `Select organization name` -> `Start typing organization name`
