### ISSUE TITLE
Github Monitoring: Monitor save-cloud and create an issue when any service is unavailable

### ISSUE THREAD

**Issue by akuleshov7** [saveourtool/save-cloud#1383]

**Comment by petertrr** [comment]
> create an issue when any service is unavailable

Isn't an issue too much? Maybe we could use alertmanager and fire notifications to a messenger?

**Comment by akuleshov7** [comment]
> > create an issue when any service is unavailable
> 
> Isn't an issue too much? Maybe we could use alertmanager and fire notifications to a messenger?

yes, too heavy and useless task
