### ISSUE TITLE
Support diktat-demo on frontend

### ISSUE THREAD

**Issue by sanyavertolet** [saveourtool/save-cloud#1423]
Right now we have a new service: `save-demo`, which has only one demo. We need to create a view for it

**Comment by nulls** [comment]
We have core functionality, sandbox and now demo. All views\pages are hosted\stored\developed in frontend. Maybe start to externalize it? To be able to run such services as a a separate application?

**Comment by sanyavertolet** [comment]
> Maybe start to externalize it? To be able to run such services as a a separate application?
You mean moving save-demo and save-sandbox to external repo as well as all the frontend and common section connected to it?

**Comment by nulls** [comment]
> > Maybe start to externalize it? To be able to run such services as a a separate application?
> 
> You mean moving save-demo and save-sandbox to external repo as well as all the frontend and common section connected to it?

Yeap. Or at least to make it possible
