### ISSUE TITLE
Filtering in history page doesn't reset current page

### ISSUE THREAD

**Issue by nulls** [saveourtool/save-cloud#1475]
We have 30 tests (for example), they are displayed on 3 pages.
We select page 2 and then select some status to filter tests. Result should be less 10 entries.
We get an empty result, because all tests on page 1, but we currently on page 2 which is not available after selecting page 1

**Comment by petertrr** [comment]
I've broken it again in #1488; haven't noticed that page reload was intended as a fix for this issue.
