### ISSUE TITLE
[DEMO] Don't rely on `curl` for downloads in `save-demo`

### ISSUE THREAD

**Issue by petertrr** [saveourtool/save-cloud#1491]
`curl` is not available in `save-demo` image and `diktat-cli` fails

cc @sanyavertolet

**Comment by sanyavertolet** [comment]
Not sure if we need it as far as the next PR java client will be used for tool download

**Comment by petertrr** [comment]
Renamed the issue, feel free to link it to an existing one and/or close if it's a duplicate
