### ISSUE TITLE
Test k8s.saveourtool.com

### ISSUE THREAD

**Issue by nulls** [saveourtool/save-cloud#1502]
1. Create a new user via github.com
2. Create a new organization
3. Create a new project in created organization
4. Create a new test sources: pylint can be taken for it https://github.com/nulls/pylint-test
5. Make a simple run with this tests

**Comment by Arrgentum** [comment]
Some pictures are not displayed
![image](https://user-images.githubusercontent.com/79669665/204846798-b15c6bae-0495-4f5d-ac2c-79a74998ff0c.png)

![image](https://user-images.githubusercontent.com/79669665/204847030-71e7e6cf-3312-4241-8cf4-baffd57e641a.png)

**Comment by petertrr** [comment]
@Arrgentum 

> Some pictures are not displayed

This is kind of expected, because we haven't moved any data outside of the DB from the old machine. You can check in the console that images are not loaded because of 404's. We should either move it (e.g. download everything, then upload using [`kubectl cp`](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#cp)) or just clear this data in the DB

**Comment by Arrgentum** [comment]
2) Create a new organization

It works

![image](https://user-images.githubusercontent.com/79669665/204853542-d8aa34c3-72d9-479d-a937-e4dba72d7e89.png)

**Comment by Arrgentum** [comment]
3) Create new project

It works

![image](https://user-images.githubusercontent.com/79669665/204854368-4ee9c6fd-1425-4872-a6f5-b177490f4a6f.png)

![image](https://user-images.githubusercontent.com/79669665/204854532-c68c16aa-7883-42bf-81b2-163992f02903.png)
Some action with project works too
![image](https://user-images.githubusercontent.com/79669665/204854735-9fc5b09c-aaff-4bfc-8ba9-787408c5b79f.png)

**Comment by Arrgentum** [comment]
When loading ProjectView gives 500 error

**Comment by Arrgentum** [comment]
If you are in the Organization View in the Tests tab, click on "create test suites source", fill in the name, do not fill in the "add new git credentioal" field and the message "You have no available git credentials in organization TestOrganization" is displayed.  Click on "submit", nothing happens, and then click on cancel, it gives a 404 error.

**Comment by Arrgentum** [comment]
4) Create a new test sources: pylint can be taken for it https://github.com/nulls/pylint-test

It works

![Screenshot from 2022-11-30 23-20-58](https://user-images.githubusercontent.com/79669665/204900329-f26afe0f-dd30-44e9-bbd9-5624430f6774.png)


![image](https://user-images.githubusercontent.com/79669665/204900271-11cd78b1-5651-42e9-950b-cc3a1a5eb85d.png)

**Comment by sanyavertolet** [comment]
Was that `k8s.saveourtool.com` or `saveourtool.com`?

**Comment by Arrgentum** [comment]
Test Suites in ```Test Suite Permission Manager``` are not displayed

**Comment by Arrgentum** [comment]
I don't know exactly how it works, but maybe since ```TestNariman``` is ```private``` and I'm not a member of it, I shouldn't be able to see it here?

![Screenshot from 2022-12-02 15-02-08](https://user-images.githubusercontent.com/79669665/205289179-046def08-f927-4516-82d1-42a6b8af966d.png)

**Comment by sanyavertolet** [comment]
> I don't know exactly how it works, but maybe since `TestNariman` is `private` and I'm not a member of it, I shouldn't be able to see it here?

We do not have private organizations maaaaan

**Comment by Arrgentum** [comment]
In the ``Test Suite Permission Manager - Visibility mode`` you can already make ```private``` test suite ```private```.

**Comment by Arrgentum** [comment]
Created 2 projects and 1 testSuite.
Both launched and after some time in the first Test Suite project in history shows:

![image](https://user-images.githubusercontent.com/79669665/205292100-ceb55084-16a0-47ad-bd89-c863ffaf9038.png)

But ExecutionView:

![image](https://user-images.githubusercontent.com/79669665/205292159-4334f5d5-8945-4a13-8084-cb99ff9c7ed2.png)

The second project Execution displays

**Comment by Arrgentum** [comment]
User permissions are not displayed correctly

picture 1:
![Screenshot from 2022-12-02 15-56-07](https://user-images.githubusercontent.com/79669665/205298428-41e9ec5c-8759-4f9f-9563-9d97858ad317.png)

picture 2:
![Screenshot from 2022-12-02 15-56-17](https://user-images.githubusercontent.com/79669665/205298496-e593cd9b-684d-45d5-b239-ec08dfe9036b.png)

**Comment by petertrr** [comment]
@Arrgentum please link any issues that are related to the problems described above. Otherwise this issue can be closed

**Comment by nulls** [comment]
@Arrgentum please update the issue

**Comment by sanyavertolet** [comment]
@Arrgentum

**Comment by sanyavertolet** [comment]
![image](https://github.com/saveourtool/save-cloud/assets/35039155/eed085b2-2e06-4522-84e6-574ca9e8404b)
