### ISSUE TITLE
Propagate CPG logs to the frontend

### ISSUE THREAD

**Issue by akuleshov7** [saveourtool/save-cloud#1504]
- [x] https://github.com/saveourtool/save-cloud/issues/1501
- [x] ~Get logs of the NEO4J with results of query execution~ discussed with @akuleshov7: it's not required for us to have logs from neo4j service taking into account our plans to migrate to another graph database
- [x] Get logs of CPG Frontend execution and put it to SAVE-CLOUD
- [x] Show errors on the frontend (the query will be constructed by @sanyavertolet ) <- you can give this task to @Cheshiriks

**Comment by nulls** [comment]
CPG logs returns as part of result and it's displayed on FE
