### ISSUE TITLE
merge all the lists of created/deleted/banned items on the ```frontend``` and do sorting by status

### ISSUE THREAD

**Issue by Arrgentum** [saveourtool/save-cloud#1537]
* logic for `state.selfOrganizationWithUserList`, `state.selfDeletedOrganizationWithUserList` and `state.selfBannedOrganizationWithUserList` looks similar. Please combine it with different by `organizationWithUsers.organization.status` or extract common places to separate methods
* Add sorting by status and re-sorting by name in group.

_Originally posted by @nulls in https://github.com/saveourtool/save-cloud/pull/1505#discussion_r1035994061_

**Comment by nulls** [comment]
logic for ordering:
```kotlin
val comparator: Comparator<OrganizationWithUsers> =
    compareBy<OrganizationWithUsers> { orderedStatus[it.organization.status] }
        .thenBy { it.organization.name }
selfOrganizationWithUserList = organizationDtos.sortedWith(comparator)
```
