### ISSUE TITLE
Support uploading of media data properly (avatars)

### ISSUE THREAD

**Issue by akuleshov7** [saveourtool/save-cloud#1558]
1. Show "loading" button
2. Add some hints for users that IN THIS FORM YOU CAN UPLOAD MEDIA. At least change ON HOVER. Now none is able to understand, that they CAN change an avatar and they need to press on the image to upload it. Need to do it for project also.
3. Rename avatar, when you save it (so we won't have errors with Cyrillic symbols)
4. Make a single hierarchy for avatars of organizations and users
5. Add some editor: https://github.com/nhn/tui.image-editor https://javascript.plainenglish.io/how-to-make-a-personal-image-editor-with-react-in-less-than-10-minutes-dba0d45ff03d

**Comment by petertrr** [comment]
Instead of renaming, `-Dsun.jnu.encoding=UTF-8 -Dfile.encoding=UTF-8` [maybe](https://stackoverflow.com/questions/39185613/java-nio-file-invalidpathexception-malformed-input-or-input-contains-unmappable)?

**Comment by akuleshov7** [comment]
I think, that we need to rename anyway
