### ISSUE TITLE
Avatar placeholders

### ISSUE THREAD

**Issue by sanyavertolet** [saveourtool/save-cloud#1562]
Right now we had an issue when avatars are unavailable for some reason and we didn't display the placeholder that does not depend on a storage. We need to display the placeholder image if real avatar in not fetched or fetched with an exception

**Comment by kgevorkyan** [comment]
What about `undraw_profile.svg` that we have?

**Comment by sanyavertolet** [comment]
Yep, but for now we do not draw it if 500 was received

**Comment by nulls** [comment]
Now the avatar endpoint returns `404` (fixed issue with `500` error)

**Comment by sanyavertolet** [comment]
> Now the avatar endpoint returns `404` (fixed issue with `500` error)

In case of missing file will the placeholder be shown?

**Comment by nulls** [comment]
> > Now the avatar endpoint returns `404` (fixed issue with `500` error)
> 
> In case of missing file will the placeholder be shown?

nope :(
