### ISSUE TITLE
Pagination doesn't work in Execution history

### ISSUE THREAD

**Issue by nulls** [saveourtool/save-cloud#1574]
https://saveourtool.com/#/CQFN.org/Diktat-Integration/history

`page` button is clickable, but nothing happens. `count` button doesn't work too

**Comment by petertrr** [comment]
Might've been broken in #1488

**Comment by kgevorkyan** [comment]
@petertrr does it worked at all before? I see, that we didn't used `usePageSelection` `useServerPaging` arguments for `tableComponent`, and also `getPageCount = null`

**Comment by kgevorkyan** [comment]
Seems, that it's really breaks after migration to `react table v8`. However, the answer is not on the surface - there are some recommendations, to set the flag `autoResetPageIndex` to `false`, but it didn't helped.

Components, which uses client side paginations does not worked, moreover, `pageIndex` changed correctly under hood, but page doesn't actually changed

**Comment by kgevorkyan** [comment]
Data from `state` seems to be updated correctly, however it doesn't influent to client side pagination, it's not worked. The configuring of several flags of `tableInstance` gives no results for now
