### ISSUE TITLE
`save-agent` and `save-cli` should be downloaded from the back-end using `HTTP GET`

### ISSUE THREAD

**Issue by 0x6675636b796f75676974687562** [saveourtool/save-cloud#1665]
Currently, the binaries get downloaded from the _back-end_ using `HTTP POST`, despite the requests don't change any state on the _back-end_ nor have any request body:

```bash
curl -vvv -X POST http://host.docker.internal:5800/internal/files/download-save-agent --output save-agent.kexe
```

We need to change `DownloadFilesController#downloadSaveAgent` and `DownloadFilesController#downloadSaveCliByVersion` on the _back-end_ as well as some _orchestrator_ logic.

**Comment by nulls** [comment]
Similarly: we use `POST` to download files and tests content. It can be changed to `GET` too

**Comment by nulls** [comment]
It was done in scope of #1830 and #1866
