### ISSUE TITLE
[EPIC] configurable demo for any project 

### ISSUE THREAD

**Issue by sanyavertolet** [saveourtool/save-cloud#1675]
Right now we have hardcoded `diktat` and `ktlint` demo. There is an idea of how to let any project owner create demo for his/her project using `save-demo`. 

## Backend TODO
 - [x] #1677
 - [x] #1682
 - [x] #1676
 - [x] #1766
 - [x] #1771
 - [x] #1785
 - [x] #1770 
 - [x] #1791
 - [x] #1755
 - [x] #1873
 - [x] Support `setup.sh` in order to set up the environment
 - [x] #1872
 - [x] #1922
 - [x] #2012

## Frontend TODO
 - [x] #1760
 - [x] #1762
 - [x] #1925

## Later improvements:
 - [x] #2032
 - [x] #1953 
 - [x] #2067 
 - [x] FIx all the bugs

## Small roadmap
![demo architecture](https://user-images.githubusercontent.com/35039155/209962423-17f94b33-8a91-4d59-8970-655857d93c96.jpg)

**Comment by nulls** [comment]
~Intergrate KubernetesManager and save-agent in order to support PodRunner~ suggestion to abstract from Kubernetes and create `OrchestratorRunner` -- it should be run on `KubernetesManager` or `DockerContainerRunner` in same manner

**Comment by sanyavertolet** [comment]
First phase is considered to be finished. As the result we have currently single-threaded executor (#2190) which is more or less fast.
