### ISSUE TITLE
Frontend: Implement storing of encrypted passwords

### ISSUE THREAD

**Issue by kentr0w** [saveourtool/save-cloud#169]

**Comment by akuleshov7** [comment]
This is a little bit related with our thoughts about security

**Comment by sanyavertolet** [comment]
@akuleshov7 as far as I understand, this one will never be done, as we are not planning to store passwords. If I am wrong, please reopen an issue

**Comment by nulls** [comment]
> @akuleshov7 as far as I understand, this one will never be done, as we are not planning to store passwords. If I am wrong, please reopen an issue

it's about Git repository and we ask to provide credentials for private repo.
User can provide token instead of password. But still we store it in database
