### ISSUE TITLE
Tests should have file_path as `TestFiles`

### ISSUE THREAD

**Issue by petertrr** [saveourtool/save-cloud#177]
SAVE operates with test resources as collections of arbitrary size. We should respect this in save-cloud and also take all files into account when calculating hash

**Comment by petertrr** [comment]
Newer versions of SAVE have `TestFiles` for this purpose

**Comment by akuleshov7** [comment]
@nulls pls check this one - probably it is already done

**Comment by nulls** [comment]
No, it didn't done.

Overview: Save create `Test` in database and store hash of a file content. We have tests with 2 files (expected as additional file). As I got, we need to add this file to calculation of hash code

**Comment by petertrr** [comment]
> we need to add this file to calculation of hash code

Yes, and also we may want to display these additional files on the frontend and so we may need to store them in the database.
