### ISSUE TITLE
Migrate `DebugInfoStorage` and `ExecutionInfoStorage` to S3

### ISSUE THREAD

**Issue by nulls** [saveourtool/save-cloud#1777]
Need to cleanup them when `TestExecution` is deleted or `Execution` is archived or deleted

**Comment by Cheshiriks** [comment]
Do you mean DebugInfoStorage and ExecutionInfoStorage?

**Comment by nulls** [comment]
> Do you mean DebugInfoStorage and ExecutionInfoStorage?

Yes, but probably I will rename the task: DebugInfo is per TestExecution, but ExecutionInfo is per Execution.
The main goal of task is migrate to S3 and remove a complex key:
- DebugInfoStorage should use `TestExecution.id` and should be clean when `TestExecution` is removed
- ExecutionInfo should use `Execution.id` and should be clean when `Execution` is removed or archived
