### ISSUE TITLE
Build and test action works for an hour

### ISSUE THREAD

**Issue by sanyavertolet** [saveourtool/save-cloud#1863]
`Build, test and upload code coverage` action sometimes works extremely long. Might be either GitHub problem or our bug. Needs to be investigated.

![screenshot](https://user-images.githubusercontent.com/35039155/218411494-36cfe519-0ef2-4221-af11-ca8051b9cea8.png)

**Comment by sanyavertolet** [comment]
The last errors found on everlasting action:
![screenshot](https://user-images.githubusercontent.com/35039155/219010103-7f3effdd-831a-4df1-808b-dd395836c9a0.png)

**Comment by kgevorkyan** [comment]
@sanyavertolet it it will reproduced, I suggest also to attach the build report, by clicking for example the following button
it contain all timelines

![image](https://user-images.githubusercontent.com/26010098/219327355-c6ab5f87-2b8d-4dab-a688-7207280b62ea.png)


we hold build artifact only for 3 days, however, this report might me available, just need to find this action

**Comment by nulls** [comment]
I suspect `gvisor runsc` as reason of handling. This step was removed.
Will continue to monitor

**Comment by nulls** [comment]
Got the same issue without `gvisor runsc`, also migrated docker tests from direct docker client to docker client in testcontainers

**Comment by sanyavertolet** [comment]
@nulls https://scans.gradle.com/s/ku36bjjl7wx3e/tests/:save-orchestrator-common:test/com.saveourtool.save.orchestrator.service.ContainerServiceTest/should%20create%20a%20container%20with%20save%20agent%20and%20test%20resources%20and%20start%20it()?top-execution=1

**Comment by nulls** [comment]
> @nulls https://scans.gradle.com/s/ku36bjjl7wx3e/tests/:save-orchestrator-common:test/com.saveourtool.save.orchestrator.service.ContainerServiceTest/should%20create%20a%20container%20with%20save%20agent%20and%20test%20resources%20and%20start%20it()?top-execution=1

we use `mockserver` to mock a response from S3 (download save-agent on start of component).
will try to migrate to testcontainers -- it should have more proper mechanism to wait till container is started

**Comment by nulls** [comment]
[Build, test and upload code coverage](https://github.com/saveourtool/save-cloud/actions/runs/4324356421/jobs/7549078535)
> The hosted runner: GitHub Actions 7 lost communication with the server. Anything in your workflow that terminates the runner process, starves it for CPU/Memory, or blocks its network access can cause this error.

More evidences that the build should be split to small pieces

**Comment by sanyavertolet** [comment]
> build should be split to small pieces

#1927

**Comment by nulls** [comment]
Will close after few weeks
