### ISSUE TITLE
Implement `PodRunner` interface

### ISSUE THREAD

**Issue by sanyavertolet** [saveourtool/save-cloud#1873]
With #1869 merged we will have almost all infrastructure to support demo runs in a separate Kubernetes pod. In order to support runs in pod, we will need to implement `PodRunner` interface that should be implemented by `DemoPodRunner`, which `run` method would trigger execution in running pod.

**Comment by kgevorkyan** [comment]
Despite the fact, that almost usually you take such issues by yourself, I suggest to add a tiny descriptions anyway

It will help to uninitiated in the details developers to understand deeply what's going on, without the need to get into the main topic, also it could help us in future, what we did at one time or another and why

**Comment by akuleshov7** [comment]
> Despite the fact, that almost usually you take such issues by yourself, I suggest to add a tiny descriptions anyway
> 
> It will help to uninitiated in the details developers to understand deeply what's going on, without the need to get into the main topic, also it could help us in future, what we did at one time or another and why

Totally agree
