### ISSUE TITLE
Request timeout on large files download

### ISSUE THREAD

**Issue by sanyavertolet** [saveourtool/save-cloud#1952]
Logs from `save-demo-agent`:

```
[ERROR]: Error while downloading files to agent: Cannot process request to save-demo: save-demo is unreachable, Request timeout has expired [url=http://demo/demo/internal/files/CQFN.org/Ktlint/download-as-zip?version=manual, request_timeout=unknown ms].
```

**Comment by sanyavertolet** [comment]
No there are two problems connected with timeouts:
1. File can bee too big to be uploaded to demo storage from backend storage;
2. setup.sh can take too much time to be executed.

The solution for the second problem is very easy - increase timeout from 3 sec to 10 min

The solution for the first problem is not that obvious. Probably we should asynchronously upload files to demo storage (should send ok 200 when the information about files to upload to save-demo storage and **before** they are uploaded to save-demo storage)

**Comment by nulls** [comment]
> The solution for the second problem is very easy - increase timeout from 3 sec to 10 min

Please do not increase timeout blindly, please make it configurable at least.
We've made timeout in 60 seconds by purpose to avoid unwanted changes in agent's container. We can't control it now, so we reduce a timeout to 1 minute

> The solution for the first problem is not that obvious. Probably we should asynchronously upload files to demo storage (should send ok 200 when the information about files to upload to save-demo storage and **before** they are uploaded to save-demo storage)

All storage logic in demo was done in async way without handlings a response: `Mono` is subscribed inside in coroutine job.
Now this upload moved fully to project reactor -- please check, you should get a response when file is uploaded

**Comment by sanyavertolet** [comment]
> Please do not increase timeout blindly, please make it configurable at least.
> We've made timeout in 60 seconds by purpose to avoid unwanted changes in agent's container. We can't control it now, so we reduce a timeout to 1 minute

I am talking about `ProcessBuilder` timeout. I think 3 seconds is not enough for `pip` to install python package (`pylint` won't be installed in 3 seconds)

**Comment by nulls** [comment]
> I think 3 seconds is not enough for `pip` to install python package (`pylint` won't be installed in 3 seconds)

`save-agent` has timeout in 60 seconds: `com.saveourtool.save.agent.SaveAgent#SETUP_SH_TIMEOUT`
`save-demo-agent` has timeout in 5 seconds: `com.saveourtool.save.demo.agent.utils.SetupUtilsKt#SETUP_SH_TIMEOUT_MILLIS`

Suggestion to use a common timeout as in `save-agent`: 60 seconds. And better to move `com.saveourtool.save.agent.AgentInitConfig` and `com.saveourtool.save.demo.DemoConfiguration`

**Comment by sanyavertolet** [comment]
> And better to move `com.saveourtool.save.agent.AgentInitConfig` and `com.saveourtool.save.demo.DemoConfiguration`

What do you mean? It seems that the entire `AgentInitConfig` is about `save-cli` and test suites while `save-demo` has nothing connected with either of these two.

**Comment by nulls** [comment]
> It seems that the entire `AgentInitConfig` is about `save-cli`

```kotlin
data class AgentInitConfig(
    val saveCliUrl: String,
    val testSuitesSourceSnapshotUrl: String,
    val additionalFileNameToUrl: Map<String, String>,
    val saveCliOverrides: SaveCliOverrides,
)
```
It's about configuration `save-agent` -- `additionalFileNameToUrl` contains `setup.sh` and url to download it. So timeout can be added to this data class (and set it to 60 seconds by default).

`save-demo-agent` doesn't have an init config file, because it download a single zip without which can contains `setup.sh` inside there. `DemoAgentConfig` is being got on start from `save-demo` and can be extended by timeout for `setup.sh`
