### ISSUE TITLE
Display demo logs on frontend

### ISSUE THREAD

**Issue by sanyavertolet** [saveourtool/save-cloud#1953]
We should display demo logs on frontend:
- [ ] On demoProjectMenu there should be a button for logs from pod with save-demo-agent
- [x] On DemoView there should be a button for execution logs (https://github.com/saveourtool/save-cloud/issues/2032)

**Comment by nulls** [comment]
We have a functionality to take logs from containers. For ref: https://github.com/saveourtool/save-cloud/issues/1503

**Comment by sanyavertolet** [comment]
> We have a functionality to take logs from containers. For ref: #1503

Actually, logs can be done with KubernetesClient also 🤔

**Comment by nulls** [comment]
> Actually, logs can be done with KubernetesClient also 🤔

Loki is the source for our logs and it contains old logs too. Also, you don't need to orchestrate container names to demo name or support cases when we have a lot instances of a single demo. Just query what's you need in loki
