### ISSUE TITLE
Move local run to MiniKube

### ISSUE THREAD

**Issue by nulls** [saveourtool/save-cloud#1967]

**Comment by sanyavertolet** [comment]
It seems that running everything in minikube is extremely slow as I found out when I was developing save-demo. The idea is to add configuration `fake-kubernetes` that would allow to use kubernetes orchestration when running spring service outside the cluster.

**Comment by nulls** [comment]
> when running spring service outside the cluster.

It is desired solution: only mysql/s3 and save-agent/save-demo-agent should be run in minikube -- the rest components should be run outside
