### ISSUE TITLE
API for automatic tests initialization

### ISSUE THREAD

**Issue by petertrr** [saveourtool/save-cloud#209]
POST a freshly built executable, e.g. from another CI

* [x] Create example http client, that supports basic API for execution submission #650 
* [x] Generate OpenAPI spec from our API https://github.com/analysis-dev/save-cloud/pull/700
* [x] Start API versioning (i.e. no breaking changes without updating major version in the spec) https://github.com/analysis-dev/save-cloud/pull/700
* [x] Support custom configuration of SKD https://github.com/analysis-dev/save-cloud/pull/715
* [x] For now authorization required OAuth token, but taking this manually might be tricky...  https://github.com/analysis-dev/save-cloud/issues/651
* [x] Expand README with set of examples with screenshots https://github.com/analysis-dev/save-cloud/pull/735
* [x] Extend logic of password creation from Frontend to Backend https://github.com/analysis-dev/save-cloud/pull/712
* [x] Change endpoints, which involved in execution, to make them more independent from low level information https://github.com/analysis-dev/save-cloud/pull/735
* [x] Make save-api more like library, to support opportunity users to use this from external applications https://github.com/analysis-dev/save-cloud/pull/752
* [x] Change API of additional file uploading, there is a lot if low level information, such ass `uploadMillis` and so on https://github.com/analysis-dev/save-cloud/pull/774
* [x] Add README for save-api library https://github.com/saveourtool/save-cloud/pull/963

**Comment by akuleshov7** [comment]
It appeared that we really need this kind of API right now

**Comment by petertrr** [comment]
I think we should also do the following:
* Generate OpenAPI spec from our API
* Start API versioning (i.e. no breaking changes without updating major version in the spec)

**Comment by petertrr** [comment]
Also, since we run execution in background and execution request returns immediately, we need a mechanism to monitor current status. It can be as simple as an endpoint with status, or more complex, something like push notifications.

**Comment by petertrr** [comment]
Another note, we can use the example client from #650 in integration tests (#94)

**Comment by akuleshov7** [comment]
@kgevorkyan please update the status. What's left?

**Comment by kgevorkyan** [comment]
@akuleshov7 Current status represented in issue description
Now I'm working on task about linking the token generation from frontend with backend, and basically after this we will get the fully working stand

The next step will cover the custom SDK configuration and README updates
