### ISSUE TITLE
Support Huawei's OAuth

### ISSUE THREAD

**Issue by nulls** [saveourtool/save-cloud#2101]
https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides/open-platform-oauth-0000001053629189

**Comment by kgevorkyan** [comment]
duplicated ? https://github.com/saveourtool/save-cloud/issues/722

**Comment by akuleshov7** [comment]
This one has a high priority

**Comment by nulls** [comment]
depends\duplicates https://github.com/saveourtool/save-cloud/issues/2185

**Comment by nulls** [comment]
but it looks like configured only for local run

**Comment by akuleshov7** [comment]
Yes, but not yet configured and supported in prod

**Comment by akuleshov7** [comment]
https://stackoverflow.com/questions/76706911/huawei-oauth-2-0-with-spring-security-causes-missing-required-parameter-client
