### ISSUE TITLE
Error page holds from broken pages to the valid ones

### ISSUE THREAD

**Issue by kgevorkyan** [saveourtool/save-cloud#2129]
If for some reasons one of the pages, for example `/demo/cpg` will be broken, after changing the page without reloading, the `Error` will still shown, despite the fact, that actually the other page is valid

**Comment by sanyavertolet** [comment]
The problem is that the response handler doesn't set error info to null on navigation to another view

**Comment by akuleshov7** [comment]
> The problem is that the response handler doesn't set error info to null on navigation to another view

who broke that? and why again?

**Comment by sanyavertolet** [comment]
> > The problem is that the response handler doesn't set error info to null on navigation to another view
> 
> who broke that? and why?

Is was broken since it was implemented. We always had to click on `Go to title page` (or something like that)

**Comment by akuleshov7** [comment]
no chance to fix it soon
