### ISSUE TITLE
Support bulk (batch) API uploading for chosen automated systems

### ISSUE THREAD

**Issue by akuleshov7** [saveourtool/save-cloud#2175]
- [x] Use dedicated token generation (same to that we have in SAVE) for particular automated systems. (@sanyavertolet).
- [x] #2313
- [x] Add UI to upload a batch with COSV files
- [x] #2504
- [x] #2521
- [x] #2506
- [x] #2508
- [x] #2525
- [x] #2538
- [x] #2543
- [x] #2548
- [x] #2561

**Comment by nulls** [comment]
> Use dedicated token generation (same to that we have in SAVE) for particular automated systems. (@sanyavertolet).

@akuleshov7, what does it mean? is it about generating ID for vulnerability in format [SOTV-2023-16](https://saveourtool.com/vuln/collection/SOTV-2023-16)?

**Comment by nulls** [comment]
> > Use dedicated token generation (same to that we have in SAVE) for particular automated systems. (@sanyavertolet).
> 
> @akuleshov7, what does it mean? is it about generating ID for vulnerability in format [SOTV-2023-16](https://saveourtool.com/vuln/collection/SOTV-2023-16)?

discussed offline: it's about basic auth using token generated by the saveourtool platfrom
