### ISSUE TITLE
Preprocessor, orcehstrator: If a repository is used both for GIT and STANDARD mode, directory will be overriden

### ISSUE THREAD

**Issue by petertrr** [saveourtool/save-cloud#222]
Because we are currently saving everything under `/home/cnb/repositories`

**Comment by kgevorkyan** [comment]
probably will be done by @nulls in his refactoring and moving to S3

**Comment by petertrr** [comment]
> probably will be done by @nulls in his refactoring and moving to S3

#857

**Comment by petertrr** [comment]
Closing due to complete rework of this part of logic
