### ISSUE TITLE
Vulnerabilities: move comments and suggestions to the review of administrators

### ISSUE THREAD

**Issue by akuleshov7** [saveourtool/save-cloud#2227]
- Right now administrators cannot ask review questions (we need to support discussion on the administrator review side)
- And when they decline the vulnerability - reporter should get advices why it was declined (notification on his side)
- It can be done in "OWNED BY ME" vulnerabilities list

**Comment by Cheshiriks** [comment]
Closed in https://github.com/saveourtool/save-cloud/pull/2325
