### ISSUE TITLE
Topbar becomes too huge

### ISSUE THREAD

**Issue by sanyavertolet** [saveourtool/save-cloud#2231]
Our topbar becomes too huge...

_Originally posted by @sanyavertolet in https://github.com/saveourtool/save-cloud/pull/2226#discussion_r1236643193_
            

We need to come up with an idea of decreasing topbar size

**Comment by nulls** [comment]
We can introduce [Hamburger button](https://en.wikipedia.org/wiki/Hamburger_button) to our topbar to reduce this size and add additional info

**Comment by akuleshov7** [comment]
Need to fix "logout" menu when we are not authorised:
<img width="369" alt="image" src="https://github.com/saveourtool/save-cloud/assets/58667063/3832c87c-8326-4626-b5c9-5efa3162a38c">

**Comment by sanyavertolet** [comment]
Yes, `Log in` might be nice. Moreover, log in might be even better if it redirects to the page on which the log in button was pressed

**Comment by sanyavertolet** [comment]
I guess this issue is completed @akuleshov7 ?
