### ISSUE TITLE
Refactor vulnerability entity

### ISSUE THREAD

**Issue by Cheshiriks** [saveourtool/save-cloud#2277]
Need delete VulnerabilityDate entity from Vulnerability entity.
It's throw exeption:

_Fetching two or more Bags(List) at the same time on an Entity could form a Cartesian Product. Since a Bag doesn't have an order.  Hibernate would not be able to map the right columns to the right entities. Hence, in this case, it throws a MultipleBagFetchException.
Link to docs: https://www.baeldung.com/java-hibernate-multiplebagfetchexception#cause-of-multiplebagfetchexception_

**Comment by akuleshov7** [comment]
huge problem, very important
