### ISSUE TITLE
Links on awesome-benchmark page cause error

### ISSUE THREAD

**Issue by akuleshov7** [saveourtool/save-cloud#2327]
https://saveourtool.com/#/archive/awesome-benchmarks/code_analysis

<img width="1728" alt="image" src="https://github.com/saveourtool/save-cloud/assets/58667063/ccf35291-4f5c-4d72-8c9e-0d217cf49d2f">

**Comment by sanyavertolet** [comment]
The logic with links to tabs was removed (so was the bug removed), here is a new issue to return it: https://github.com/saveourtool/save-cloud/issues/2402
