### ISSUE TITLE
Support deletion of users from SAVE platform

### ISSUE THREAD

**Issue by akuleshov7** [saveourtool/save-cloud#2343]
Users should be able to delete their accounts

**Comment by Cheshiriks** [comment]
There are many questions here:
- what to do with organizations / projects of the user, where he is the owner?
- what to do with user vulnerabilities?

**Comment by Cheshiriks** [comment]
Now we have cascade deletion configured in the database. This can lead to the fact that we are ALL that is somehow tied to this user

**Comment by nulls** [comment]
we have `User.isActive`. We can deactivate instead of deleting

**Comment by akuleshov7** [comment]
Vlad implemented it in https://github.com/saveourtool/save-cloud/pull/2361
Now need to think about the Frontend
