### ISSUE TITLE
Backend: Support uploading files one-by-one instead of storing in a single FormData

### ISSUE THREAD

**Issue by petertrr** [saveourtool/save-cloud#235]
* ~When file is added, it should be uploaded to the server, stored in temporary location and the path should be returned to the frontend~
* ~Instead of sending all files as one FormData part, provide only paths to uploaded files in FormData~
* ~File is then retrieved from it's location, when backend processes execution request~
* If temporary file hasn't been used for some time (1 hour?), it is deleted

**Comment by petertrr** [comment]
Other than retention, done in #242

**Comment by akuleshov7** [comment]
Need to configure retention process

**Comment by petertrr** [comment]
Can be closed in favor of https://github.com/saveourtool/save-cloud/issues/857
