### ISSUE TITLE
Fix whitelabel error page for the gateway

### ISSUE THREAD

**Issue by akuleshov7** [saveourtool/save-cloud#2376]
Now if you will emulate Internal error - you will see Whitelabel page even though we have `error.html` in place.
But the main problem is about 404: any dummy requests to `http://localhost:5300/blablabla` will just cause 401, but not 404 that we could have handled properly on the frontend.

**Comment by sanyavertolet** [comment]
TBD: https://www.baeldung.com/spring-boot-custom-error-page
