### ISSUE TITLE
Update all stubs in the project

### ISSUE THREAD

**Issue by akuleshov7** [saveourtool/save-cloud#2378]
Change all stubs to the following: 
- This organization has not reported any Vulnerabilities yet

And then Big Beautiful button:
"But you can submit it here"

And that is everywhere

_Originally posted by @akuleshov7 in https://github.com/saveourtool/save-cloud/issues/2374#issuecomment-1651978636_

**Comment by akuleshov7** [comment]
I think button delete selected contest should be shown only if we click at least one select button from contest list
in case of empty contests it definitely should be hidden

**Comment by akuleshov7** [comment]
not sure about the borders, probably placeholders will looks better without them (?) Kirill

**Comment by akuleshov7** [comment]
May be add sad cat animation

**Comment by sanyavertolet** [comment]
> May be add sad cat animation

Think it is inappropriate here, either pure text or some nice animation but not crying cat
