### ISSUE TITLE
Prohibit different languages as identifiers on the frontend 

### ISSUE THREAD

**Issue by sanyavertolet** [saveourtool/save-cloud#2434]
We do not prohibit Chinese names (and Russian as well), but the topbar displays it as `%...%...` encoding. We should deal with different encodings properly.

**Comment by nulls** [comment]
we cannot use backend with user with non-latin letters, looks like the issue is in encoding urls

**Comment by nulls** [comment]
discussed offline: better to prohibit it everywhere and allow only ASCII
