### ISSUE TITLE
Bug in TableComponent

### ISSUE THREAD

**Issue by Cheshiriks** [saveourtool/save-cloud#2449]
The button to go to the last page does not work. Clicking this button will take you to the first page.

<img width="464" alt="000" src="https://github.com/saveourtool/save-cloud/assets/50615459/465c1499-e1c6-44c1-b524-38cf8fa5dd83">

**Comment by akuleshov7** [comment]
Also still see overflow

**Comment by akuleshov7** [comment]
Fixed
