### ISSUE TITLE
Limit user's registration in the Vulnerabilities Archive

### ISSUE THREAD

**Issue by akuleshov7** [saveourtool/save-cloud#2451]
1. New Users and Organizations should be approved after registration in the system. 
2. We should be able to ban users
3. All checks should be done inside a common logic in gateway

#### upd:
Vlad has partially done the task. Here is what remains:
- [x] https://github.com/saveourtool/save-cloud/pull/2546
- [x] https://github.com/saveourtool/save-cloud/pull/2552
- [x] https://github.com/saveourtool/save-cloud/pull/2553
- [x] https://github.com/saveourtool/save-cloud/pull/2560
- [x] https://github.com/saveourtool/save-cloud/pull/2562
- [x] https://github.com/saveourtool/save-cloud/pull/2565

### What's done:
- https://github.com/saveourtool/save-cloud/pull/2503
- https://github.com/saveourtool/save-cloud/pull/2489

**Comment by nulls** [comment]
btw, we have `/api/` which is hidden under authorization, but also we have a set of endpoints which we open by listing them in the special list in WebConfig.
Maybe introduce a new sub-path: `/public-api/` and open it instead of a list of open endpoints

**Comment by akuleshov7** [comment]
@Cheshiriks is it done?

**Comment by sanyavertolet** [comment]
Done
