### ISSUE TITLE
Support files upload for vulnerabilities on the frontend

### ISSUE THREAD

**Issue by akuleshov7** [saveourtool/save-cloud#2509]
We urgently need support for three buttons to facilitate the bulk upload of data through three entry points. This functionality should be implemented as a common VFC/FC, which will be utilized in three distinct locations:

- [x] Above the 'Propose Vulnerability' view.
- [x] At the organization level: on the page where vulnerability submissions are made.
- [x] Near to the 'Propose Vulnerability' PLUS icon in the Organization Collection list view.

- [x] The 'Upload' button should only be accessible to users belonging to organizations that have been granted the '**can do bulk upload of vulnerabilities**' privilege set by the SuperUser in the settings. To verify this permission, we require each user to be checked with a 'permissionControllerEvaluator' on the backend that will provide all the information. This evaluator will return a data class containing a field named 'isPermittedToBulkUpload'." 

- [x] Temporary storage 
- [x] Added endpoint for deleting file
- [x] endpoints should return a _FileDtoResponse_

Of course all permissions should also be checked on the backend as well.

**Comment by sanyavertolet** [comment]
@Cheshiriks please take a look at `simpeFileUploader`, it might help

**Comment by akuleshov7** [comment]
@Cheshiriks @nulls if we cannot read file (there is a mistake in any file) - you need to propagate it to the FE

**Comment by akuleshov7** [comment]
@nulls also check this one
