### ISSUE TITLE
Criticality polishing

### ISSUE THREAD

**Issue by akuleshov7** [saveourtool/save-cloud#2517]
- [x] Add a string field for Vector of Attack on Propose new vulnerability (urgent) https://github.com/saveourtool/save-cloud/pull/2569
- [x] Change the criticality to a float number in range 1 to 10 (urgent) https://github.com/saveourtool/save-cloud/pull/2585
- [x] Calculate criticality from vector of attack https://github.com/saveourtool/save-cloud/pull/2580
- [x] Create a online criticality calculator UI https://github.com/saveourtool/save-cloud/pull/2606

**Comment by akuleshov7** [comment]
@nulls also wanted to make a library for this in future

**Comment by nulls** [comment]
@Cheshiriks did you support cvss v2?
