### ISSUE TITLE
Polishing left column in vulnerability view

### ISSUE THREAD

**Issue by akuleshov7** [saveourtool/save-cloud#2519]
- [ ] Editing of info should work properly: now it does not work for all fields.
- [x] Editing of vulnerabilities on the backend should be done with **versioning**
- [ ] We need extra information: propagate `aliases` to the frontend. 
- [ ] The second step is to **approve aliases** by vuln owners, so no one will add some invalid links.
- [x] All collaborators/acknowledgement that are added on SAVE frontend should be added to credits with a link to SAVE profile, this is how we will distinguish these users from the imported users in credits outside of our platform.
- [x] Show Credits on the frontend after Collaborators section (just text is enough)
- [ ] Show Related Vulnerabilities: related[]: List of String
- [x] Show CWE : `cwe_ids[]`
- [x] Description editing should be prohibited for regular users at least in the beginning, later we will change it probably

**Comment by akuleshov7** [comment]
@nulls pls review it also

**Comment by nulls** [comment]
partially implemented, created a follow up issue

**Comment by nulls** [comment]
I guess, the last point is alredy done by https://github.com/saveourtool/save-cloud/pull/2733/files#diff-31fcdbfdf73acb391c8a15c7b3f047326a0658733a348bb492f322dad3a4e52eR176

_Originally posted by @kgevorkyan in https://github.com/saveourtool/save-cloud/issues/2790#issuecomment-1775436474_
