### ISSUE TITLE
Invalid processing when multiple suites

### ISSUE THREAD

**Issue by akuleshov7** [saveourtool/save-cloud#2628]
- Selecting multiple suites for this benchmark: https://github.com/saveourtool/GSAC-SAVE/
- Causes: 
```
private fun Collection<TestSuiteVersioned>.extractIdsAndVersion() = this.map(TestSuiteVersioned::id) to this.map(TestSuiteVersioned::version).takeIf { it.isNotEmpty() }?.single()

```

to fail

**Comment by akuleshov7** [comment]
Also can you please fix this small problem under this issue: 

https://github.com/saveourtool/save-cloud/assets/58667063/5fb99a24-0b17-4a33-a3c6-8d9453261045

**Comment by nulls** [comment]
Preselect is long task, will extract it to a separate issue
