### ISSUE TITLE
Support rollback for `edit` of view

### ISSUE THREAD

**Issue by akuleshov7** [saveourtool/save-cloud#2668]
Now, when the cross is pressed, the view is not rolled back.
Also saving of state will help us not to submit a Vulnerability, when it is not changed

**Comment by nulls** [comment]
Creating a new version as a suggestion instead of applying changes resolves this issue

**Comment by akuleshov7** [comment]
@DrAlexD covered it already. @DrAlexD please link a PR here.

**Comment by DrAlexD** [comment]
Done in #2740
