### ISSUE TITLE
Unify the code which renders the table of vulnerabilities

### ISSUE THREAD

**Issue by 0x6675636b796f75676974687562** [saveourtool/save-cloud#2746]
- `com/saveourtool/save/frontend/components/basic/organizations/OrganizationVulnerabilitiesTab.kt`
 - `com/saveourtool/save/frontend/components/views/userprofile/UserProfileVulnerabilitiesTab.kt`
 - `com/saveourtool/save/frontend/components/views/vuln/VulnerabilityCollectionView.kt`

**Comment by nulls** [comment]
https://github.com/saveourtool/save-cloud/issues/2715#issuecomment-1764267617

**Comment by 0x6675636b796f75676974687562** [comment]
> Additionally, need to implement: [#2715 (comment)](https://github.com/saveourtool/save-cloud/issues/2715#issuecomment-1764267617)

Created:

 - #2782
