### ISSUE TITLE
Different size of columns on vuln list view

### ISSUE THREAD

**Issue by kgevorkyan** [saveourtool/save-cloud#2769]
With logged user the size of columns is different

![1](https://github.com/saveourtool/save-cloud/assets/26010098/d2c0e156-d19c-40f4-a471-fa1afd3e2f57)

while in case of logout user they are the same

![2](https://github.com/saveourtool/save-cloud/assets/26010098/6cca890b-3d4e-4992-9d5c-054d3d6f1001)

Probably it could be fixed

Other problem - initial page size is `7` despite the fact, that `entries` is set to `10`

@DrAlexD

**Comment by akuleshov7** [comment]
Extended the minHeight
