### ISSUE TITLE
Invalid COSV format in `GHSA-cr45-98w9-gwqx`

### ISSUE THREAD

**Issue by nulls** [saveourtool/save-cloud#2775]
Error: `Failed to process raw COSV file with id: 26586 is due to Field 'score' is required for type with serial name 'com.saveourtool.osv4k.Severity', but it was missing`

https://osv.dev/vulnerability/GHSA-cr45-98w9-gwqx

```json
  "severity": [
    {
      "type": "CVSS_V3",
      "score": ""
    }
  ],
```

**Comment by akuleshov7** [comment]
Field `score` is provided (with empty string). Why you decoder failed with that error?

**Comment by nulls** [comment]
> Field `score` is provided (with empty string). Why you decoder failed with that error? (I did not understood the text of an error).
> 
> Anyway - I have reported it here: [google/osv.dev#1740](https://github.com/google/osv.dev/issues/1740)

I already raised PR for it: https://github.com/github/advisory-database/pull/2873

**Comment by nulls** [comment]
> Why you decoder failed with that error? (I did not understood the text of an error).

Write a test and it doesn't fail. So I looked at file again: https://osv-vulnerabilities.storage.googleapis.com/PyPI/GHSA-cr45-98w9-gwqx.json
```
  "severity": [
    {
      "type": "CVSS_V3"
    }
  ]
```

The file is score is missed in JSON
