### ISSUE TITLE
Default `Changes` for COSV files should be between different versions

### ISSUE THREAD

**Issue by nulls** [saveourtool/save-cloud#2777]
The `Changes` tag shows diff with the same versions, better to show between last one and last one minus 1

![image](https://github.com/saveourtool/save-cloud/assets/1164369/6c643ec1-6b6b-4ad3-b5b2-9e9f5c9d1437)

There is no unified diff.

And there a small place for a diff:
![image](https://github.com/saveourtool/save-cloud/assets/1164369/bd268c98-3df3-4fbe-969c-c0721ddfa69c)

_Originally posted by @nulls in https://github.com/saveourtool/save-cloud/issues/2715#issuecomment-1764251317_

**Comment by kgevorkyan** [comment]
if history is empty, `changes` tab shoulbe disabled
