### ISSUE TITLE
The list of `cosv submitter` field is hidden by filter below `organization`

### ISSUE THREAD

**Issue by nulls** [saveourtool/save-cloud#2780]
With current filter location
the list of `cosv submitter` field is hidden by filter below `organization`

also, what is tag? there is no such column in table

![Untitled](https://github.com/saveourtool/save-cloud/assets/26010098/8aaaeda1-0fc8-48fc-884b-eb53d57121f5)

_Originally posted by @kgevorkyan in https://github.com/saveourtool/save-cloud/issues/2715#issuecomment-1764351370_

**Comment by akuleshov7** [comment]
https://github.com/saveourtool/save-cloud/pull/2783
