### ISSUE TITLE
Vulnerability database, owner tab: COSV Submitter is always the current user. It can be omitted from the table

### ISSUE THREAD

**Issue by 0x6675636b796f75676974687562** [saveourtool/save-cloud#2782]
Vulnerability database, owner tab &mdash; COSV Submitter is always the current user. It can be omitted from the table

![image](https://github.com/saveourtool/save-cloud/assets/1164369/02ab78aa-9a91-4102-8497-07d31435a8b0)

_Originally posted by @nulls in https://github.com/saveourtool/save-cloud/issues/2715#issuecomment-1764267617_

**Comment by kgevorkyan** [comment]
https://github.com/saveourtool/save-cloud/pull/2824
