### ISSUE TITLE
`ERROR` after clicking on the buttons to go to `Customize profile`, `Settings`, `Manage organizations`

### ISSUE THREAD

**Issue by DrAlexD** [saveourtool/save-cloud#2847]
`ERROR` after clicking on the button to go to `Customize profile` on `UserProfile` page and on the buttons to go to `Settings` and `Manage organizations` from navigation bar at the top of the page.

![image](https://github.com/saveourtool/save-cloud/assets/29813548/3d318f46-b3fc-4fd1-b5f7-d7040fb21bd8)

**Comment by kgevorkyan** [comment]
after reloading the error disappear, but only for a while

**Comment by nulls** [comment]
The same issue was with loading `translation` #2834
