### ISSUE TITLE
Agent: Support sending large execution logs / debug info in several POST requests

### ISSUE THREAD

**Issue by petertrr** [saveourtool/save-cloud#298]
```
500 Server Error for HTTP POST "/executionLogs"
org.springframework.core.io.buffer.DataBufferLimitException: Exceeded limit on max bytes to buffer : 262144
	at org.springframework.core.io.buffer.LimitedDataBufferList.raiseLimitException(LimitedDataBufferList.java:98)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint ? org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
	|_ checkpoint ? HTTP POST "/executionLogs" [ExceptionHandlingWebHandler]
Stack trace:
```

**Comment by petertrr** [comment]
It might make sense to change request type from plain JSON with text to multipart/form-data

**Comment by akuleshov7** [comment]
> It might make sense to change request type from plain JSON with text to multipart/form-data

You think we need to put logs into the compressed file?

**Comment by akuleshov7** [comment]
I do not think that multipart data will work good with a data in a serializable data class: 
https://stackoverflow.com/questions/69628364/kotlin-ktor-request-class-for-multipart-form-data

**Comment by petertrr** [comment]
> You think we need to put logs into the compressed file? Or you suggest to use binary format @petertrr

I think, at first we can try to send them as `multipart` instead of `application/json`, because for multipart Spring has different receiving logic without data size limits. ktor-client should be able to do this: https://ktor.io/docs/request.html#upload_file.

**Comment by kgevorkyan** [comment]
> > You think we need to put logs into the compressed file? Or you suggest to use binary format @petertrr
> 
> I think, at first we can try to send them as `multipart` instead of `application/json`, because for multipart Spring has different receiving logic without data size limits. ktor-client should be able to do this: https://ktor.io/docs/request.html#upload_file.
> 
> Compression of text data should also help, but it can be added later and be sent as multipart/form-data as well

Why do not simply increase the limits for now by `spring.codec.max-in-memory-size`?

**Comment by petertrr** [comment]
> Why do not simply increase the limits for now by `spring.codec.max-in-memory-size`?

It will still lead to possibly undetermined behavior, some new combination of tools and test suites might introduce even greater amounts of data.

**Comment by akuleshov7** [comment]
> > You think we need to put logs into the compressed file? Or you suggest to use binary format @petertrr
> 
> I think, at first we can try to send them as `multipart` instead of `application/json`, because for multipart Spring has different receiving logic without data size limits. ktor-client should be able to do this: https://ktor.io/docs/request.html#upload_file.
> 
> Compression of text data should also help, but it can be added later and be sent as multipart/form-data as well

right now we are reaching the limit of 0.2Mb, seriously? :)
Just change the limit on the backend and that's all. 100Mb is fine

**Comment by akuleshov7** [comment]
Oh, I looked into the code, this data class should have never exist. We read file -> store logs into JSON -> serialize -> transfer -> deserialize -> write into the file on backend

**Comment by kgevorkyan** [comment]
Temporary solution provided in https://github.com/analysis-dev/save-cloud/pull/569, by increasing the limits of buffer,
changing `content type` in https://github.com/analysis-dev/save-cloud/pull/568 require more investigations. Problem, probably, because of https://youtrack.jetbrains.com/issue/KTOR-2947
