### ISSUE TITLE
Save cloud should be able to process and calculate properly skipped tests 

### ISSUE THREAD

**Issue by orchestr7** [saveourtool/save-cloud#308]
![image](https://user-images.githubusercontent.com/58667063/136588565-fed7fc6b-c07d-4e78-9755-7dc7646c5bda.png)

This test was run with the following excluded tests:
```
    excludedTests = ["readability-isolate-declaration-no-infinite-loop.cpp", "checkers/readability-isolate-declaration-no-infinite-loop.cpp"]

```

But it was not calculated

**Comment by petertrr** [comment]
This is actually a problem on save-core's side. On save-cloud we merely reflect data from the JSON report, produced by save-core. Save-core should treat excluded tests as skipped
