### ISSUE TITLE
For `STANDARD` executions store version of standard suites repo

### ISSUE THREAD

**Issue by petertrr** [saveourtool/save-cloud#321]
Now we are saving file name as a stub in `DownloadProjectController.saveBinaryFile`. It should be git revision of standard suites repo, because file names are already stored in execution after #244 .

* Store revision per repository, that has been used (we support running test suites from different repos)
* If commit for rerun is different from current HEAD, clone it once again into a fresh location

**Comment by nulls** [comment]
will be covered in #958

**Comment by petertrr** [comment]
Closing as #958 is completed
