### ISSUE TITLE
Frontend & Backend: Use `BrowserRouter` instead of `HashRouter`

### ISSUE THREAD

**Issue by petertrr** [saveourtool/save-cloud#364]
It looks like `BrowserRouter` is [newer and better](https://stackoverflow.com/a/51976069) alternative, which gives access to a rich History API. I will require some tweaks on backend, namely backend's API should be moved to `/api/*` group of endpoints, and `index.html` should be served for all other requests.

Links:
* push state routing: https://github.com/paketo-buildpacks/nginx/blob/c9c1487623e5f22f93585809c43e48f441f5f662/assets/default.conf#L173-L178

### What's done:
- [x] Change all `href`s to `Link`s and `navigate`s, thus removing `#/` prefix everywhere
- [x] https://github.com/saveourtool/save-cloud/pull/2381
- [x] https://github.com/saveourtool/save-cloud/pull/2383 (locally tested)
- [x] Test with Kubernetes cluster
- [x] https://github.com/saveourtool/save-cloud/pull/2403

**Comment by akuleshov7** [comment]
We are ready for it.
But need to check endpoints naming clash with backend.

**Comment by sanyavertolet** [comment]
There is some [problem](https://github.com/remix-run/react-router/blob/v4.1.1/FAQ.md#why-doesnt-my-application-render-after-refreshing) right now. Need to come up with a nice solution.

**Comment by sanyavertolet** [comment]
Still need to test with our cluster

**Comment by akuleshov7** [comment]
Closing it, @sanyavertolet ?

**Comment by sanyavertolet** [comment]
> Closing it, @sanyavertolet ?

Yes, seems to be done and works fine.
