### ISSUE TITLE
File attributes are lost in rerun mode

### ISSUE THREAD

**Issue by kgevorkyan** [saveourtool/save-cloud#442]
Because during rerun we download files from our storage, where there is no any attributes on files

**Comment by kgevorkyan** [comment]
For now it's roughly covered in https://github.com/diktat-static-analysis/save-cloud/pull/441 by marking all files executable

**Comment by akuleshov7** [comment]
@kgevorkyan please handle it properly, ok? pls put into your backlog

**Comment by petertrr** [comment]
Rerun logic is completely overhauled in recent commits, so this issue must've been resolved along the way
