### ISSUE TITLE
Liquibase quality checks: add into CI

### ISSUE THREAD

**Issue by petertrr** [saveourtool/save-cloud#464]
Starting with version 4.5.0 liquibase has [quality checks](https://docs.liquibase.com/concepts/advanced/quality-checks.html), which are like static analysis for liquibase changesets. We should investigate possibilities and integrate into our CI. It's a low-priority infra-related issue.

**Comment by akuleshov7** [comment]
If you got a chance to work with latest liquibase - @nulls @icemachined may be you will be able to give suggestions related to this

**Comment by nulls** [comment]
@akuleshov7, nope, I'm not familiar with latest liquebase
