### ISSUE TITLE
Backend: separate backend update and upload logic from the frontend API

### ISSUE THREAD

**Issue by akuleshov7** [saveourtool/save-cloud#494]
Gateway issue.

We should split it into different logic: we need some microservice that would be used only for FRONTEND and EXTERNAL API purposes.
All internal logic should be encapsulated in internal microservices

**Comment by petertrr** [comment]
external API service should handle all `/api` queries and user identity validation
internal API service should handle all `/internal` queries and other stuff, like scheduled jobs
