### ISSUE TITLE
Frontend: Check if debug info exists before displaying the active link

### ISSUE THREAD

**Issue by petertrr** [saveourtool/save-cloud#515]
Also, if debug info is not present, display something instead of an empty page

**Comment by akuleshov7** [comment]
This is about the debug info that is available for all tests on the executionView. 
Also while the assignee of this issue will investigate it - probably he will help with making this view more user-friendly.

**Comment by akuleshov7** [comment]
<img width="1727" alt="image" src="https://user-images.githubusercontent.com/58667063/168488610-dbf0e123-c604-4050-a48e-eba7602e24e1.png">

@petertrr could you please investigate why we are getting 404 now?

**Comment by akuleshov7** [comment]
and 400 for Pending executions OH, @petertrr welcome to hell

<img width="1727" alt="image" src="https://user-images.githubusercontent.com/58667063/168489084-358bd47c-0480-4b1d-9bbf-cedbcfbd4874.png">

**Comment by petertrr** [comment]
> <img alt="image" width="1727" src="https://user-images.githubusercontent.com/58667063/168488610-dbf0e123-c604-4050-a48e-eba7602e24e1.png">
> 
> @petertrr could you please investigate why we are getting 404?

I believe these particular executions have been run through another instance of save-backend, and because of this debug info files are not available for our usual backend. Should've cleaned those executions up in time..

**Comment by petertrr** [comment]
> and 400 for Pending executions OH, @petertrr welcome to hell

This one is because `agentContainerId` is null in requests. And it's null there, because it's null in the fetched data, because execution must've hanged at some point.

**Comment by akuleshov7** [comment]
> > and 400 for Pending executions OH, @petertrr welcome to hell
> 
> This one is because `agentContainerId` is null in requests. And it's null there, because it's null in the fetched data, because execution must've hanged at some point.

We should handle properly all errors in this case… Not friendly

**Comment by petertrr** [comment]
> We should handle properly all errors in this case… Not friendly

I believe for this we should also prioritize #331 to properly display errors for executions that fail early.

**Comment by petertrr** [comment]
With #760 every test execution in the table has `hasDebugInfo` property. This property should be used on the frontend to set correct appearance of rows and link for debug info. Also, while `agentId` is null, link for debug info should also be disabled.

cc @akuleshov7

**Comment by petertrr** [comment]
Resolved in #893 by @akuleshov7
