### ISSUE TITLE
Rerun doesn't work for execution, that has previously failed before `testSuiteIds` have been set

### ISSUE THREAD

**Issue by petertrr** [saveourtool/save-cloud#529]
```
 java.lang.NullPointerException: null
at org.cqfn.save.backend.controllers.ExecutionController.getTestRootPathByTestSuites(ExecutionController.kt:244)
```
Somewhat expected, but it's confusing. E.g. #331 can help, but it's an error in backend.

**Comment by akuleshov7** [comment]
@kgevorkyan look at this with a priority. It’s your functionality

**Comment by petertrr** [comment]
@akuleshov7 actually it's quite a rare case, when we had an early-stage internal error and execution becomes corrupt. I think we can at least log this more explicitly, than simple NPE, but actual fix is not that critical.

**Comment by petertrr** [comment]
This issue is invalid since we moved from setting test root path to using test suite sources
