### ISSUE TITLE
ProjetcView: `Warning: Cannot update during an existing state transition`

### ISSUE THREAD

**Issue by petertrr** [saveourtool/save-cloud#560]
Now we are getting a warning on `ProjectView`:
```
Warning: Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state.
    at div
    at div
    at eval (...)
    at div
    at div
    at ProjectView 
```
because we are calling `setState` somewhere inside `render` itself

**Comment by akuleshov7** [comment]
Dime, sorry for assigning this issue on you, but it is more related to coroutines and KotlinJS than to the frontend. 
Will be a good issue to become familiar with KotlinJS

**Comment by akuleshov7** [comment]
should be fixed
