### ISSUE TITLE
ci: Error when processing detekt SARIF reports

### ISSUE THREAD

**Issue by sanyavertolet** [saveourtool/save-cloud#608]
While doing task #194 it was found out that if detekt detects no problems, task `Code scanning results / detekt` says 
```
Error when processing the SARIF file
This check concluded as neutral.
```
But if detekt finds problems, task is marked as succesful.

**Comment by kgevorkyan** [comment]
It could be occurred probably because of some limitations on Github, in https://github.com/analysis-dev/save-cloud/pull/597 disable posting of sarif reports, in case, when there is no any code style issue

**Comment by petertrr** [comment]
Now we have an unresolved code style error: https://github.com/analysis-dev/save-cloud/security/code-scanning/722 :)
But since it appeared only because of Actions' internal errors, this issue can be closed and the alert dismissed manually

**Comment by nulls** [comment]
> @nulls seems, that this is already done a lot of time ago, isn't it?

yes, we have a task to merge detekt's reports
