### ISSUE TITLE
Add source field to UserInfo

### ISSUE THREAD

**Issue by sanyavertolet** [saveourtool/save-cloud#656]
We need to add `source` field to `data class UserInfo` in order to tell one user from another user with same nickname but different platform (e.g. github, gitlab etc).

**Comment by sanyavertolet** [comment]
Added fields `source` and `projects` in #652. Need to process `source` field at backend because for now we just cut out it.

**Comment by petertrr** [comment]
Also all endpoints that are now consuming `userName` as parameter should also consume source.

**Comment by sanyavertolet** [comment]
@akuleshov7 do we still want it to be done?

**Comment by petertrr** [comment]
@sanyavertolet do you mean that we don't need `source` to identify a user, because we plan to force names to be unique in #915?

**Comment by sanyavertolet** [comment]
> @sanyavertolet do you mean that we don't need `source` to identify a user, because we plan to force names to be unique in #915?

exactly

**Comment by petertrr** [comment]
Closing because in #915 we'll switch to a unique usernames per save-cloud which will be linked with original login-source pairs
