### ISSUE TITLE
Bug: wrong redirect when super admin confirms his rights in projectSettingsMenu

### ISSUE THREAD

**Issue by sanyavertolet** [saveourtool/save-cloud#784]

**Comment by sanyavertolet** [comment]
> Where does it redirect the user to now?

Now there is only one button. If super admin clicks on it, it means he knows he has extra rules. So no redirect is done.

**Comment by petertrr** [comment]
> So no redirect is done.

No, I mean without your fix. Where would the user be redirected? In the linked PR I see logic about changing double-button window to a single-button, but I don't see any logic related to redirects, only an empty handler for `GLOBAL_ROLE_CONFIRM`

**Comment by sanyavertolet** [comment]
> > So no redirect is done.
> 
> No, I mean without your fix. Where would the user be redirected? In the linked PR I see logic about changing double-button window to a single-button, but I don't see any logic related to redirects, only an empty handler for `GLOBAL_ROLE_CONFIRM`

Oh yeah, there was a redirect to executions because I processed wrong enum entry (`HistoryView`, I guess).
