### ISSUE TITLE
Support Windows agents in SAVE-cloud cluster

### ISSUE THREAD

**Issue by akuleshov7** [saveourtool/save-cloud#785]
Right now the save-agent is build with Linux64 target. 

This sometimes leads to a confusion: some of tools that we can check can be native applications built for Windows. 
In this case it is very important to be able to run container with an agent on Windows.

Probably it can be linked with Kubernetes related tasks, @petertrr? or it can be solved by docker only?

**Comment by petertrr** [comment]
No way, neither Docker nor Kubernetes will support this out of the box. This would require a container runtime that runs a virtual machine and still has the same interface as usual CRI compliant container. Moreover, running a VM will require additional setup for system components and maybe even some restrictions on hardware. I'm not familiar with technologies that combine VMs and containers, but I'm sure those exist.

**Comment by akuleshov7** [comment]
Oh, my bad, of course Docker does not support Windows host. 
Never will be implemented. But may be there will be some VMs one day for such purposes...

**Comment by akuleshov7** [comment]
Won't be done
