### ISSUE TITLE
Rework modal windows

### ISSUE THREAD

**Issue by sanyavertolet** [saveourtool/save-cloud#803]
We need to refactor existing modals:

> These things can be refactored: converted to a `FC` with props containing all these settings, and renamed from `run...Modal` to something like `singleButtonModal` and `doubleButtonModal`. Can be done as a separate PR

_Originally posted by @petertrr in https://github.com/saveourtool/save-cloud/pull/799#discussion_r884958740_

**Comment by akuleshov7** [comment]
not critical, can be done later

**Comment by sanyavertolet** [comment]
Now there are two variants of how I see it:
1. We should try using browser windows like `window.alert()` or `window.confirm()` - this is a nice option, but the only problem is that `Chrome` does it not that good
2. We should implement one `modalBuilder` that uses bootstrap styles with custom button amount, generated by `buttonBuilder`

For now I like the second idea more.
