### ISSUE TITLE
Support testing of redirects logic

### ISSUE THREAD

**Issue by petertrr** [saveourtool/save-cloud#805]
On frontend, we often use redirects by modifying `window.location` directly. This approach is hard to cover by unit tests.
Another possible approach is to use `Link`/`NavLink` components from `react-router` and wrap components under test in `MemoryRouter`.
We should investigate differences between these two options and find a way to perform unit tests to check if redirects are actually called when we expect them to be.

**Comment by akuleshov7** [comment]
Will never be done. Instead of weeks spent on this task much easier to test it manually
