### ISSUE TITLE
LoadingHandler follow-ups

### ISSUE THREAD

**Issue by petertrr** [saveourtool/save-cloud#826]
* Organization settings view hangs on loading after page refresh
* Loading animation is not displayed when number of entries in a table is changed (e.g. `show 10 entries` -> `show 100 entries`: there seems to be a loading period, but no animation is displayed)

**Comment by sanyavertolet** [comment]
Talking about loading modal on `ExecutionView`, I should say that it was decided to leave the view with `noopLoadingHandler`. In this issue it will be fixed.

**Comment by petertrr** [comment]
In `fileUploader` we have a separate progress bar, but now the default loading animation overlaps it
