### ISSUE TITLE
Frontend: flaky tests

### ISSUE THREAD

**Issue by sanyavertolet** [saveourtool/save-cloud#831]
Sometimes `ProjectViewTest` fails both on CI and locally. Need to be investigated.

**Comment by sanyavertolet** [comment]
Closed with #832

**Comment by petertrr** [comment]
A lot of flaky runs on CI, still needs investigation

**Comment by sanyavertolet** [comment]
@petertrr haven't seen flaky frontend tests for a long time, guess you fixed it
