### ISSUE TITLE
`ProjectSettingsMenu`: confusing design

### ISSUE THREAD

**Issue by petertrr** [saveourtool/save-cloud#849]
1. Click `Add git credentials` (btw, it's already confusing because this window allows the user to change existing git connection as well as existing credentials)
2. Change something
3. Click `Save`
4. Confusion: do we need to click `Save changes` once again? Can we discard changes in Git info by clicking `Cancel`?

**Comment by nulls** [comment]
`Add git credentials` was removed from project settings
