### ISSUE TITLE
Redirect missing 404 requests to a proper 404 page on the frontend

### ISSUE THREAD

**Issue by akuleshov7** [saveourtool/save-cloud#912]
If you go to saveourtool.com/#/hui you should be redirected to 404 page.
Same with projects, with executions and ALL pages that are missing.

**Comment by akuleshov7** [comment]
http://localhost:8080/#/dfhdf/settings/dsf

**Comment by akuleshov7** [comment]
Please fix some of invalid redirects (for example when we search a user in the list)

**Comment by sanyavertolet** [comment]
Let's say we get a 404 error visiting page that doesn't exist (e.g. link looks like this http://localhost:8080/#/project). After we try to go to another page after we got 404 without page refreshing, we still get 404 (even on http://localhost:8080/#/)

**Comment by akuleshov7** [comment]
@Cheshiriks is it done?

**Comment by akuleshov7** [comment]
if yes - please close

**Comment by Cheshiriks** [comment]
For now, I'll leave it open. It remains to fix the not yet big tank when moving through the TopBar from page 404
