### ISSUE TITLE
Problem of username selection: improvements

### ISSUE THREAD

**Issue by akuleshov7** [saveourtool/save-cloud#915]
Right now we give user exactly the same name/id, that he has in the initial system (codehub/github). 
We need to support two main things on the frontend:
1) "Registration"-like page, where user will be able to change/update his nickname OR use one we have suggested;
2) Possibility to change nick-name (if it is not yet used by other people).

**Comment by akuleshov7** [comment]
Important task

**Comment by petertrr** [comment]
It's also crucial to keep the original login in the database to be able to identify future logins. If we want to support merging multiple OAuth login under the same account, this `original_login` column may become a list in the future
