### ISSUE TITLE
Owner of organization probably should be able to delete projects

### ISSUE THREAD

**Issue by akuleshov7** [saveourtool/save-cloud#917]
I know, that we have discussed that an owner of the Organization cannot manipulate with the project. 
But right now we have a situation when user can block the "DELETION" of organization only because it was "locked" by some other guy who has created a project (and owner cannot delete it).

We need to support the logic of deletion of projects by OWNER, so Owner of organization should have an access to the Projects inside this organization.

**Comment by akuleshov7** [comment]
@Arrgentum please have a look at that

**Comment by Arrgentum** [comment]
There is a problem with navigating to the tab addresses in the OrganizationView.kt @akuleshov7 

In the App.kt address of the tab in OrganizationView.kt has the form:
path = "/:owner/:the tab"
Address of the project name in OgranizationView.kt has the form:
path = "/:owner/:name"

The React router cannot determine where to go.

In my opinion, the best solution is register these tab addresses (tools, tests, info, settings) separately and prohibit the creation of projects with such names
