### ISSUE TITLE
Infra: Create integration test for save-cloud

### ISSUE THREAD

**Issue by petertrr** [saveourtool/save-cloud#94]
Test should start with `/trigger` endpoint invocation, check that test source is fetched (or should it be fetched beforehand with current architecture?), tests are discovered, containers are started, batches are distributed, containers are terminated at the end.

We have an API for that. We need some GitHub bot or ANY tool that you could suggest for our integration testing with `saveourtool.com` .

Other from that, it should also cover the following scenarios:
* Submit execution with testing type: PUBLIC
* Submit execution with testing type: PRIVATE
* Submit execution with testing type: CONTEST_MODE
* Submit rerun for all the above;

We have a client library for save and a task to revive it: https://github.com/saveourtool/save-cloud/issues/1061 - this is what you will need to check during this task. Because probably the best variant for us is to enhance this tool and use it for testing. Also it can be needed later for your task with SAVE GitHub integration.

**I suggest to make decomposition of this task and split it to:**
1) phase 1: [some tool, better save-api-cli] (https://github.com/saveourtool/save-cloud/tree/master/save-api-cli) using save-client connects to SAVEOURTOOL endpoints. Useful docs: https://github.com/saveourtool/save-cloud/blob/master/save-backend/Backend-API.md (please note, that this API is not updated, so there can be some gaps that you will need to cover)
1.5) Fix found issues in `save-api`
2) phase 2: create a GitHub bot (simply a scheduled action?) that runs these tests once each week (or manually to perform smoke tests after a large release)

**Comment by 0x6675636b796f75676974687562** [comment]
[Scheduled runs](https://github.com/0x6675636b796f75676974687562/save-backend-tests/actions/workflows/test.yml?query=event%3Aschedule+branch%3Amaster).

**Comment by 0x6675636b796f75676974687562** [comment]
[First successful run](https://github.com/0x6675636b796f75676974687562/save-backend-tests/actions/runs/3242742619).

Source code: [0x6675636b796f75676974687562/save-backend-tests](https://github.com/0x6675636b796f75676974687562/save-backend-tests).

Closing.
