### ISSUE TITLE
500 /projects/stub/N/A/users/roles

### ISSUE THREAD

**Issue by nulls** [saveourtool/save-cloud#947]
ProjectView requests roles for current user and fails with 500 when runs it with stub project.
It was fixed by changing using of `state.project` to local resolved `project`, but needs to fix original error too

**Comment by sanyavertolet** [comment]
We started to notice this problem because of react 18 new feature - setState is now batched (https://github.com/reactwg/react-18/discussions/21)

**Comment by nulls** [comment]
it doesn't affect directly, can be done with low priority

**Comment by sanyavertolet** [comment]
We need to carefully look through all the view we have to be sure that it doesn't affect us. The point is that state updates in the end of `setState` method. We simply need to use local variables
