### ISSUE TITLE
After creation of a new tool for organization, tool git url is not available from anywhere

### ISSUE THREAD

**Issue by kgevorkyan** [saveourtool/save-cloud#972]
Currently, for each organization we have the set of `git url`
![1](https://user-images.githubusercontent.com/26010098/181214130-b8e96f29-a466-48f2-8e59-e6619c28d389.PNG)

Which we can choose for execution.

However, if we will create new tool **for this organization** with **some new** `git url`, and try to evaluate this tool, this `git url` won't appear anywhere.

The only way to use it - only add it manually in **organization** settings

After creation of a new tool, git url **should** automatically appear in list of available `git url`

**Comment by nulls** [comment]
Git url from project creation will be moved. It will be moved to Organization setting page.
Git url is for tests, project is for evaluated tools. It was decided that git url doesn't relate to project

**Comment by nulls** [comment]
The fields was removed from the view for creation project: 765a74cc76fa0119a64dee8c7033dbcef2e1be5c
