### ISSUE TITLE
In organization settings make it clearer why the git url from git credentials list is not available for modification

### ISSUE THREAD

**Issue by kgevorkyan** [saveourtool/save-cloud#973]
![1](https://user-images.githubusercontent.com/26010098/181219615-73477278-d351-444f-9d8f-278e84262fbf.PNG)

**Comment by petertrr** [comment]
@nulls I believe it's your implementation, what are the reasons for this code?
https://github.com/saveourtool/save-cloud/blob/3a7cd4eab11e032d3870e9623402160602c6fde2/save-frontend/src/main/kotlin/com/saveourtool/save/frontend/components/basic/organizations/GitWindow.kt#L91

**Comment by nulls** [comment]
git url is unique key for git dto -- modification of it means remove one and create a new one.
there is another button:  `Add new`. It allows to set git url and credentials

**Comment by petertrr** [comment]
> git url is unique key for git dto

Yeah, that makes sense. I think we should make it more clear for the user, though. For example, a tooltip on the frontend, that would describe that this field is immutable, or we can just make it look differently - not like a disabled `input` but like a textfield of something.
