### ISSUE TITLE
Removing of additional files should require confirmation

### ISSUE THREAD

**Issue by kgevorkyan** [saveourtool/save-cloud#986]
Now it's kind of easy to misclick the button and accidentally remove the file

![Capture](https://user-images.githubusercontent.com/26010098/182149716-d08b881a-5c08-494b-acb7-e5990686d47d.PNG)

**Comment by kgevorkyan** [comment]
Also, if it is not already done, this operation should be available only for admins

**Comment by akuleshov7** [comment]
Please at least make confirmation
